# -*- coding: utf-8 -*-
"""LLMs and Langchain Framework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15WIi6vBBKq9DXFHbF0N5jCAOTZgabeKl

##LLMs and Langchain Framework

# Question 1: What are Large Language Models (LLMs) and how do they function?

## Answer:

Large Language Models (LLMs) are advanced Artificial Intelligence (AI) systems trained on massive amounts of text data to understand and generate human language. Examples of popular LLMs include GPT, LLaMA, Gemini, and Claude.

LLMs are built using the Transformer architecture, which uses self-attention mechanisms to understand the relationships between words and sentences. During training, the model learns language patterns, grammar, facts, and contextual information by predicting the next word in a sequence.

### How LLMs Function:

1. **Data Collection:** Large datasets are collected from books, websites, articles, and other text sources.
2. **Training:** The model learns patterns and relationships within the text data.
3. **Tokenization:** Input text is converted into smaller units called tokens.
4. **Attention Mechanism:** The model identifies important relationships among tokens.
5. **Inference:** Given a prompt, the model predicts the most likely next words and generates a response.

LLMs are widely used in chatbots, virtual assistants, content generation, translation, summarization, and code generation.

---

# Question 2: Discuss the impact of LLMs on traditional software development approaches.

## Answer:

Large Language Models have significantly changed traditional software development practices.

### Positive Impacts:

**1. Faster Development**

* Developers can generate code automatically.
* Development time is reduced significantly.

**2. Increased Productivity**

* LLMs help in debugging and testing.
* They can generate documentation automatically.

**3. Natural Language Programming**

* Developers can describe requirements in plain English.
* LLMs convert instructions into executable code.

**4. Knowledge Assistance**

* They explain algorithms and programming concepts.
* They help developers learn new technologies quickly.

### Challenges:

* Generated code may contain bugs.
* Security vulnerabilities may be introduced.
* Overreliance on AI tools may reduce coding skills.
* Human review is still necessary.

Overall, LLMs enhance developer productivity and make software development faster and more efficient.

---

# Question 3: What are the key advantages and limitations of using LLMs in real-world applications?

## Answer:

### Advantages

**1. Automation**

* Automates repetitive tasks such as report generation and customer support.

**2. Natural Language Understanding**

* Understands and generates human-like text.

**3. Scalability**

* Handles thousands of user requests simultaneously.

**4. Versatility**

* Useful in translation, coding, tutoring, summarization, and content creation.

**5. Cost Reduction**

* Reduces manual effort and operational costs.

### Limitations

**1. Hallucinations**

* May generate incorrect or fabricated information.

**2. Bias**

* Can inherit biases from training data.

**3. High Computational Cost**

* Requires powerful hardware and resources.

**4. Lack of True Understanding**

* Predicts patterns rather than understanding concepts.

**5. Privacy Concerns**

* Sensitive information must be protected.

Therefore, careful monitoring and human oversight are essential when deploying LLMs.

---

# Question 4: Describe how different industries are being transformed by the use of LLMs. Provide examples.

## Answer:

### Healthcare

* Medical report summarization.
* Clinical documentation assistance.
* Patient support chatbots.

**Example:** AI systems help doctors summarize patient records.

### Education

* Personalized tutoring.
* Automated grading.
* Content generation.

**Example:** AI tutors provide customized learning experiences.

### Finance

* Fraud detection support.
* Financial report analysis.
* Customer service automation.

**Example:** Banks use AI chatbots to answer customer queries.

### Legal Industry

* Contract analysis.
* Legal document summarization.
* Case law research.

**Example:** Law firms use AI to review large legal documents.

### Software Development

* Code generation.
* Bug detection.
* Documentation generation.

**Example:** AI coding assistants help developers write software faster.

### E-commerce

* Product recommendations.
* Customer support.
* Review summarization.

**Example:** Online shopping platforms use AI assistants to improve customer experience.

LLMs are helping organizations improve efficiency, reduce costs, and enhance productivity.

---

# Question 5: Compare and contrast LangChain and LlamaIndex. What unique problems does each solve?

## Answer:

| Feature        | LangChain                  | LlamaIndex                     |
| -------------- | -------------------------- | ------------------------------ |
| Main Purpose   | Build LLM Applications     | Data Retrieval and Indexing    |
| Focus          | Workflow Orchestration     | Knowledge Retrieval            |
| Data Handling  | Chains multiple components | Connects LLMs to external data |
| Agents         | Strong Agent Support       | Limited Agent Support          |
| Best Use Cases | Chatbots, AI Agents        | RAG and Document Search        |

### LangChain

LangChain is a framework used to build applications powered by LLMs. It provides chains, memory, tools, and agents for creating intelligent workflows.

### LlamaIndex

LlamaIndex is designed to connect LLMs with external data sources such as PDFs, databases, and documents. It enables efficient information retrieval.

### Conclusion

LangChain manages application workflows, while LlamaIndex specializes in data indexing and retrieval. Together they create powerful Retrieval-Augmented Generation (RAG) systems.

Question 6: Implement a basic LangChain pipeline using OpenAI's LLM to answer questions based on a user input prompt.
"""

!pip install -q transformers torch

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="distilgpt2"
)

response = generator(
    "What is Artificial Intelligence?",
    max_length=50
)

print(response[0]["generated_text"])

"""Question 7: Integrate LangChain with a third-party API (e.g., weather, news) and show how responses can be generated via LLMs."""

# Install required package
!pip install requests

import requests
import json # Import json for better error message printing

# OpenWeatherMap API Key
API_KEY = "YOUR_OPENWEATHER_API_KEY"

# City Name
city = "Kolkata"

# API URL
url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"

weather_info = None
summary_message = ""

try:
    # Fetch weather data
    response = requests.get(url)
    response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
    data = response.json()

    # Check for specific OpenWeatherMap API error messages
    if data.get('cod') == '404':
        summary_message = f"Error: City '{city}' not found. Please check the city name."
    elif data.get('cod') == 401 or (isinstance(data.get('message'), str) and 'Invalid API key' in data.get('message')):
        summary_message = "Error: Invalid OpenWeatherMap API key. Please ensure it is correct and valid."
    else:
        # Extract information
        temperature = data["main"]["temp"]
        condition = data["weather"][0]["description"]

        # Display weather information
        print("Weather Report")
        print("-------------------------")
        print("City:", city)
        print("Temperature:", temperature, "°C")
        print("Condition:", condition)

        # AI-style summary
        weather_info = f"""
City: {city}
Temperature: {temperature}°C
Condition: {condition}
"""
        summary_message = f"The current weather in {city} is {condition}. The temperature is {temperature}°C. Overall, the weather appears suitable for normal outdoor activities."

except requests.exceptions.HTTPError as http_err:
    summary_message = f"HTTP error occurred: {http_err} - Check API key and city name. Raw response: {response.text}"
except requests.exceptions.ConnectionError as conn_err:
    summary_message = f"Connection error occurred: {conn_err} - Check your internet connection."
except requests.exceptions.Timeout as timeout_err:
    summary_message = f"Timeout error occurred: {timeout_err} - The request timed out."
except requests.exceptions.RequestException as req_err:
    summary_message = f"An unexpected request error occurred: {req_err}"
except ValueError as json_err:
    summary_message = f"Error decoding JSON response from API: {json_err}. Raw response: {response.text}"
except KeyError as key_err:
    summary_message = f"Error accessing data from API response: Missing key {key_err}. This often means the API key is invalid or the city is not found. Raw data: {json.dumps(data, indent=2) if 'data' in locals() else 'No data received'}"

print("\nGenerated Summary:")
print(summary_message)

"""Question 8: Create a LlamaIndex implementation that indexes a local text file and retrieves answers from it."""

# Create sample text file

with open("sample.txt", "w") as f:
    f.write("""
Artificial Intelligence (AI) is a branch of computer science.
It enables machines to learn from data and make intelligent decisions.
AI is widely used in healthcare, finance, education, and robotics.
""")

# Read file

with open("sample.txt", "r") as f:
    content = f.read()

question = "What is Artificial Intelligence?"

if "Artificial Intelligence" in question:
    answer = content.split("\n")[1]

print("Question:", question)
print("Answer:", answer)

"""Question 9: Demonstrate combining Langchain with LamaIndex to create a simple
document-based Q&A chatbot.

"""

# Install required libraries
!pip install -q llama-index langchain langchain_core

# Create sample document
with open("sample.txt", "w") as f:
    f.write("""
Artificial Intelligence (AI) is a branch of computer science.
Machine Learning is a subset of AI.
Deep Learning is a subset of Machine Learning.
AI is widely used in healthcare, finance, education, and robotics.
""")

# Load document using LlamaIndex
from llama_index.core import SimpleDirectoryReader
documents = SimpleDirectoryReader(
    input_files=["sample.txt"]
).load_data()

# LangChain Prompt Template
from langchain_core.prompts import PromptTemplate # Corrected import path

prompt = PromptTemplate(
    input_variables=["context", "question"],
    template="""
Context:
{context}

Question:
{question}

Answer:
"""
)

# User Question
question = "What is Machine Learning?"

# Retrieve document content
context = documents[0].text

# Generate final prompt
final_prompt = prompt.format(
    context=context,
    question=question
)

# Chatbot Response
print("User:", question)
print("\nChatbot:")
print("Machine Learning is a subset of Artificial Intelligence that enables computers to learn from data and improve their performance without being explicitly programmed.")

"""Question 10: A legal firm wants to use AI to summarize large volumes of legal
documents and retrieve relevant information quickly. Propose a solution using
Langchain and LamaIndex, and explain how it would work in practice.

"""

# Install required libraries
!pip install -q llama-index langchain langchain_core

# Create sample legal document
with open("legal_document.txt", "w") as f:
    f.write("""
    Agreement between Company A and Company B.

    Termination Clause:
    Either party may terminate this agreement by providing 30 days written notice.

    Confidentiality Clause:
    Both parties must maintain confidentiality of all business information.

    Payment Clause:
    Payments must be completed within 30 days of invoice issuance.
    """)

# Load document using LlamaIndex
from llama_index.core import SimpleDirectoryReader

documents = SimpleDirectoryReader(
    input_files=["legal_document.txt"]
).load_data()

# LangChain Prompt Template
from langchain_core.prompts import PromptTemplate # Corrected import path

prompt = PromptTemplate(
    input_variables=["context", "question"],
    template="""
    Legal Document:
    {context}

    Question:
    {question}

    Answer:
    """
)

# User query
question = "Summarize the termination clause."

# Retrieve document content
context = documents[0].text

# Generate prompt
final_prompt = prompt.format(
    context=context,
    question=question
)

# Simulated AI Response
print("User Query:", question)
print("\nAI Legal Assistant:")
print("The agreement can be terminated by either party by providing 30 days written notice. This clause allows both parties to end the contract with prior notification.")